spring:
  application:
    name: spring-movie-api
  datasource:
    username: root
    password: Admin@123
    url: jdbc:mysql://192.168.0.112:3306/movies
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

project:
  poster: posters/


base:
  url: "http://localhost:8080"